# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d3d4dc7
_src_path: https://github.com/scipp/copier_template.git
description: Visualization library for Scipp
max_python: '3.13'
min_python: '3.10'
namespace_package: ''
nightly_deps: scipp
orgname: scipp
prettyname: Plopp
projectname: plopp
related_projects: Scipp,Scippneutron,Ess
year: 2025
