# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022 Scipp contributors (https://github.com/scipp)

from .common import require_interactive_backend, preprocess
from .figure import figure
from ..core import input_node, node, Node
from ..core.utils import coord_as_bin_edges
from ..widgets import PointsTool

import scipp as sc
from numpy import ndarray
from typing import Union, Dict, List, Literal


def inspector(obj: Union[sc.typing.VariableLike, ndarray],
              dim: str = None,
              *,
              operation: Literal['sum', 'mean', 'min', 'max'] = 'sum',
              crop: Dict[str, Dict[str, sc.Variable]] = None,
              **kwargs):
    """
    Inspector takes in a three-dimensional input and applies a reduction operation
    (`sum` by default) along one of the dimensions specified by `dim`.
    It displays the result as a two-dimensional image.
    In addition, an 'inspection' tool is available in the toolbar which allows to place
    markers on the image which perform slicing at that position to retain only the third
    dimension and displays the resulting one-dimensional slice on the right hand side
    figure.

    Controls:
    - Click to make new point
    - Drag existing point to move it
    - Middle-click to delete point

    Parameters
    ----------
    obj:
        The object to be plotted.
    dim:
        The dimension along which to apply the reduction operation. This will also be
        the dimension that remains in the one-dimensional slices generated by adding
        markers on the image. If no dim is provided, the last (inner) dim of the input
        data will be used.
    operation:
        The operation to apply along the third (undisplayed) dimension specified by
        `dim`.
    crop:
        Set the axis limits. Limits should be given as a dict with one entry per
        dimension to be cropped. Each entry should be a nested dict containing scalar
        values for `'min'` and/or `'max'`. Example:
        `da.plot(crop={'time': {'min': 2 * sc.Unit('s'), 'max': 40 * sc.Unit('s')}})`
    **kwargs:
        See :py:func:`plopp.plot` for the full list of figure customization arguments.

    Returns
    -------
    :
        A :class:`Box` which will contain two :class:`Figure` and one slider widget.
    """
    if obj.ndim != 3:
        raise ValueError('The inspector plot currently only work with '
                         f'three-dimensional data, found {obj.ndim} dims.')
    require_interactive_backend('inspector')

    from plopp.widgets import SliceWidget, slice_dims, Box
    da = preprocess(obj, crop=crop, ignore_size=True)

    a = input_node(da)
    if dim is None:
        dim = da.dims[-1]

    # Convert dimension coords to bin edges
    for d in set(da.dims) - set([dim]):
        da.coords[d] = coord_as_bin_edges(da, d)

    op_node = node(getattr(sc, operation), dim=dim)(a)
    f2d = figure(op_node, **{**{'crop': crop}, **kwargs})
    xdim = f2d._dims['x']['dim']
    ydim = f2d._dims['y']['dim']

    f1d = figure()
    event_nodes = {}

    def make_node(change):
        event = change['event']
        event_node = Node(
            func=lambda: {
                xdim: sc.scalar(event.xdata, unit=da.meta[xdim].unit),
                ydim: sc.scalar(event.ydata, unit=da.meta[ydim].unit)
            })
        event_nodes[event_node.id] = event_node
        change['artist'].nodeid = event_node.id
        inspect_node = slice_dims(a, event_node)
        f1d.graph_nodes[inspect_node.id] = inspect_node
        inspect_node.add_view(f1d)
        f1d.render()

    def update_node(change):
        event = change['event']
        n = event_nodes[change['artist'].nodeid]
        n.func = lambda: {
            xdim: sc.scalar(event.xdata, unit=da.meta[xdim].unit),
            ydim: sc.scalar(event.ydata, unit=da.meta[ydim].unit)
        }
        n.notify_children(change)

    def remove_node(change):
        n = event_nodes[change['artist'].nodeid]
        pnode = n.children[0]
        f1d._children[pnode.id].remove()
        f1d.draw()
        pnode.remove()
        n.remove()

    pts = PointsTool(ax=f2d._ax, tooltip='Add inspector points')
    pts.points.on_create = make_node
    pts.points.on_vertex_move = update_node
    pts.points.on_remove = remove_node
    f2d.toolbar['inspect'] = pts
    return Box([[f2d, f1d]])
