# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

package:
  name: plopp

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - matplotlib
    - python>=3.9

test:
  imports:
    - plopp
  requires:
    - ipympl
    - ipywidgets
    - mpltoolbox
    - pandas
    - pytest
    - python-graphviz
    - pythreejs
    - scipp
    - scipy
    - xarray
  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/plopp
  license: BSD-3-Clause
  summary: Visualization library for Scipp
  description: Visualization library for Scipp
  dev_url: https://github.com/scipp/plopp
  doc_url: https://scipp.github.io/plopp
