name: Build

on:
  workflow_call:

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  build_conda:
    name: Conda build
    runs-on: 'ubuntu-22.04'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # history required so setuptools_scm can determine version

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: build-env
          create-args: >-
            conda-build
            boa
      - run: conda mambabuild --channel conda-forge --channel scipp --no-anaconda-upload --override-channels --output-folder conda/package conda

      - uses: actions/upload-artifact@v4
        with:
          name: conda-package-noarch
          path: conda/package/noarch/*.tar.bz2

  build_wheels:
    name: Wheels
    runs-on: 'ubuntu-22.04'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # history required so setuptools_scm can determine version

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.github/workflows/python-version-ci'

      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/wheels.txt

      - name: Build wheels
        run: python -m build

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
