name: Formatting

on:
  workflow_call:
    inputs:
      python-version:
        type: string

jobs:
  formatting:
    name: Formatting and static analysis
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      - uses: pre-commit-ci/lite-action@v1.0.2
        if: always()
        with:
          msg: Apply automatic formatting
