name: Main

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  formatting:
    uses: ./.github/workflows/formatting.yml

  tests:
    name: Tests
    needs: [setup, formatting]
    # strategy:
    #   matrix:
    #     os: ['ubuntu-22.04']
    #     python:
    #       - version: '${{needs.setup.outputs.min_python}}'
    #         tox-env: '${{needs.setup.outputs.min_tox_env}}'
    uses: ./.github/workflows/test.yml
    with:
      # os-variant: ${{ matrix.os }}
      python-version: ${{ needs.setup.outputs.min_python }}
      tox-env: 'test' # ${{ matrix.python.tox-env }}
    secrets: inherit

  docs:
    needs: tests
    uses: ./.github/workflows/docs.yml
    with:
      publish: false
      linkcheck: true
    secrets: inherit

  build_packages:
    needs: tests
    uses: ./.github/workflows/build.yml
