name: Setup

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      min_python:
        value: ${{ jobs.setup.outputs.min_python }}
      # min_tox_env:
      #   value: ${{ jobs.setup.outputs.min_tox_env }}
      release_tag:
        value: ${{ jobs.setup.outputs.release_tag }}

jobs:
  setup:
    name: Variables
    runs-on: 'ubuntu-22.04'
    outputs:
      min_python: ${{ steps.vars.outputs.min_python }}
      # min_tox_env: ${{ steps.vars.outputs.min_tox_env }}
      release_tag: ${{ steps.release.outputs.release_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # history required so we can determine latest release tag
      - name: Get Python version for other CI jobs
        id: vars
        run: |
          echo "min_python=$(cat .github/workflows/python-version-ci)" >> $GITHUB_OUTPUT
      - name: Get last release tag from git
        id: release
        run: echo "release_tag=$(git describe --tags --abbrev=0 --match '[0-9]*.[0-9]*.[0-9]*')" >> $GITHUB_OUTPUT

          # echo "min_tox_env=py$(cat .github/workflows/python-version-ci | sed 's/\.//g')" >> $GITHUB_OUTPUT